# Generated by Django 5.2.16 on 2026-08-13 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the entity.', max_length=50, verbose_name='name')),
                ('active', models.BooleanField(default=True, help_text='Indicates if the entity is active.', verbose_name='active')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the entity.', max_length=50, verbose_name='name')),
                ('active', models.BooleanField(default=True, help_text='Indicates if the entity is active.', verbose_name='active')),
                ('inventory_number', models.CharField(help_text='Inventory number of the equipment.', max_length=20, verbose_name='inventory number')),
                ('sequence_number', models.PositiveSmallIntegerField(help_text='Sequence number of the equipment.', verbose_name='sequence number')),
                ('company', models.ForeignKey(help_text='Company that owns the equipment.', on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='equipment.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'equipment',
                'verbose_name_plural': 'equipments',
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the entity.', max_length=50, verbose_name='name')),
                ('active', models.BooleanField(default=True, help_text='Indicates if the entity is active.', verbose_name='active')),
                ('company', models.ForeignKey(help_text='Company that owns the spare part.', on_delete=django.db.models.deletion.PROTECT, related_name='spare_parts', to='equipment.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'spare part',
                'verbose_name_plural': 'spare parts',
            },
        ),
    ]
