# Generated by Django 5.2.16 on 2026-08-13 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='unit',
            field=models.ForeignKey(help_text='Unit of measurement for the spare part.', on_delete=django.db.models.deletion.PROTECT, related_name='spare_parts', to='invoices.unit', verbose_name='unit'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('company', 'inventory_number'), name='unique_inventory_number_per_company'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('company', 'name', 'sequence_number'), name='uniq_equipment_sequence_per_company_and_name'),
        ),
    ]
