# Generated by Django 5.2.16 on 2026-08-13 08:48

import core.mixins
import core.utils
import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(help_text='Invoice number as shown on the document.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='number')),
                ('date', models.DateField(help_text='Date of the invoice.', verbose_name='date')),
                ('company', models.ForeignKey(help_text='The company to which this invoice belongs.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='equipment.company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-date'],
            },
            bases=(core.mixins.FullCleanSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InvoiceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(help_text='Version number of the invoice.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this version was created.')),
                ('file', models.FileField(help_text='Uploaded invoice file (excel).', upload_to=core.utils.invoice_file_path, validators=[core.validators.validate_invoice_file], verbose_name='file')),
                ('invoice', models.ForeignKey(help_text='The invoice to which this version belongs.', on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'invoice version',
                'verbose_name_plural': 'invoice versions',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceParsingError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Error message describing the parsing issue.', validators=[django.core.validators.MaxLengthValidator(500)], verbose_name='message')),
                ('row', models.PositiveIntegerField(help_text='Row number where error occurred, or NULL if the error is not row-specific.', null=True, verbose_name='row')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the error was recorded.', verbose_name='created at')),
                ('version', models.ForeignKey(help_text='The invoice version associated with this parsing error.', on_delete=django.db.models.deletion.PROTECT, related_name='parsing_errors', to='invoices.invoiceversion', verbose_name='invoice version')),
            ],
            options={
                'verbose_name': 'invoice parsing error',
                'verbose_name_plural': 'invoice parsing errors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='active_version',
            field=models.ForeignKey(blank=True, help_text='The currently active version of the invoice.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for_invoice', to='invoices.invoiceversion', verbose_name='active version'),
        ),
        migrations.CreateModel(
            name='ReportMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Year of the reporting period.', validators=[django.core.validators.MinValueValidator(2000)])),
                ('month', models.IntegerField(help_text='Month of the reporting period.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт'), ('editing', 'На редакции')], default='open', help_text='Current status of the reporting period.', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Date and time when the reporting period was first closed.', null=True)),
                ('start_date', models.DateField(help_text='First day of the reporting period.')),
                ('end_date', models.DateField(blank=True, help_text='Last day of the reporting period.', null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, help_text='Date and time of the last modification.')),
            ],
            options={
                'verbose_name': 'report month',
                'verbose_name_plural': 'report months',
                'ordering': ['-year', '-month'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month'), name='uniq_report_month_year_month'), models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('status',), name='uniq_open_report_month')],
            },
            bases=(core.mixins.FullCleanSaveMixin, models.Model),
        ),
        migrations.AddField(
            model_name='invoice',
            name='report_month',
            field=models.ForeignKey(help_text='The report month to which this invoice belongs.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.reportmonth', verbose_name='report month'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the unit (e.g., 'kilogram').", max_length=50, verbose_name='name')),
                ('symbol', models.CharField(help_text="Symbol of the unit (e.g., 'kg').", max_length=20, verbose_name='symbol')),
                ('aliases', models.JSONField(blank=True, default=list, help_text='List of alternative names for the unit, used to recognize it in invoices.', verbose_name='aliases')),
            ],
            options={
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'symbol'), name='uniq_unit_name_symbol')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of the item in the specified unit, with up to two decimal places.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='quantity')),
                ('spare_part', models.ForeignKey(help_text='The spare part associated with this invoice item.', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='equipment.sparepart', verbose_name='spare part')),
                ('version', models.ForeignKey(help_text='The invoice to which this item belongs.', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='invoices.invoiceversion', verbose_name='invoice')),
                ('unit', models.ForeignKey(blank=True, help_text='Measurement unit of the item. Can be empty if not recognized.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_items', to='invoices.unit', verbose_name='unit')),
            ],
            options={
                'verbose_name': 'invoice item',
                'verbose_name_plural': 'invoice items',
                'ordering': ['-version__invoice__date', 'spare_part__name'],
            },
            bases=(core.mixins.FullCleanSaveMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WriteOffFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity of spare parts written off.', max_digits=10, verbose_name='quantity')),
                ('fact_date', models.DateField(help_text='Date when the write-off occurred.', verbose_name='fact date')),
                ('equipment_name', models.CharField(help_text='Name of the equipment at the time of write-off.', max_length=50, verbose_name='equipment name')),
                ('equipment_inventory_number', models.CharField(help_text='Inventory number of the equipment at the time of write-off.', max_length=50, verbose_name='inventory number')),
                ('equipment_sequence_number', models.PositiveSmallIntegerField(help_text='Sequence number of the equipment at the time of write-off.', verbose_name='sequence number')),
                ('equipment_company_name', models.CharField(help_text='Company owning the equipment at the time of write-off.', max_length=50, verbose_name='company name')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the write-off fact was created.', verbose_name='created at')),
                ('source', models.CharField(choices=[('invoice', 'Invoice'), ('manual', 'Manual')], help_text='Source of the write-off: invoice or manual entry.', max_length=20, verbose_name='source')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled')], default='active', help_text='Status of the write-off fact for corrections.', max_length=20, verbose_name='status')),
                ('invoice_item', models.ForeignKey(blank=True, help_text='Optional invoice item that was the source of this write-off.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='write_off_facts', to='invoices.invoiceitem', verbose_name='invoice item')),
                ('report_month', models.ForeignKey(help_text='The report month to which this fact belongs.', on_delete=django.db.models.deletion.PROTECT, related_name='write_off_facts', to='invoices.reportmonth', verbose_name='report month')),
                ('spare_part', models.ForeignKey(help_text='The spare part that was written off.', on_delete=django.db.models.deletion.PROTECT, related_name='write_off_facts', to='equipment.sparepart', verbose_name='spare part')),
            ],
            options={
                'verbose_name': 'write-off fact',
                'verbose_name_plural': 'write-off facts',
                'ordering': ['-fact_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoiceversion',
            constraint=models.UniqueConstraint(fields=('invoice', 'version'), name='uniq_invoice_version_per_invoice'),
        ),
        migrations.AddIndex(
            model_name='invoiceparsingerror',
            index=models.Index(fields=['version'], name='invoices_in_version_dc2ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceparsingerror',
            index=models.Index(fields=['created_at'], name='invoices_in_created_0a6127_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('number', 'report_month'), name='uniq_invoice_number_per_report_month'),
        ),
    ]
