# Generated by Django 5.2.16 on 2026-08-20 13:27

import core.utils
import core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_initial'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date'], 'verbose_name': 'накладная', 'verbose_name_plural': 'накладные'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'ordering': ['-version__invoice__date', 'spare_part__name'], 'verbose_name': 'строка накладной', 'verbose_name_plural': 'строки накладной'},
        ),
        migrations.AlterModelOptions(
            name='invoiceversion',
            options={'ordering': ['-version'], 'verbose_name': 'версия накладной', 'verbose_name_plural': 'версии накладных'},
        ),
        migrations.AlterModelOptions(
            name='reportmonth',
            options={'ordering': ['-year', '-month'], 'verbose_name': 'отчётный период', 'verbose_name_plural': 'отчётные периоды'},
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='uniq_invoice_number_per_report_month',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='nomenclature_number',
            field=models.CharField(blank=True, help_text='Номенклатурный номер запчасти, указанный в документе.', max_length=30, null=True, verbose_name='номенклатурный номер'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='released_quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Фактически отпущенное количество запчасти.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='отпущенное количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='requested_quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Количество запчасти, указанное в колонке «Затребовано».', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='затребованное количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Общая сумма по строке накладной.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='сумма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_code',
            field=models.CharField(blank=True, help_text='Код единицы измерения, указанный в документе.', max_length=30, null=True, verbose_name='код единицы измерения'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Цена одной единицы запчасти, указанная в документе.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена за единицу'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceversion',
            name='warehouse_keeper',
            field=models.CharField(blank=True, help_text='ФИО кладовщика, указанное в накладной.', max_length=50, null=True, verbose_name='кладовщик'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='active_version',
            field=models.ForeignKey(blank=True, help_text='Текущая активная версия накладной.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_for_invoice', to='invoices.invoiceversion', verbose_name='активная версия'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(help_text='Компания, к которой относится накладная.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='equipment.company', verbose_name='компания'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(help_text='Дата накладной, указанная в документе.', verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(help_text='Номер накладной, указанный в документе.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='номер'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='report_month',
            field=models.ForeignKey(help_text='Отчётный период, к которому относится накладная.', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.reportmonth', verbose_name='отчётный период'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='spare_part',
            field=models.ForeignKey(help_text='Запчасть, указанная в строке накладной.', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='equipment.sparepart', verbose_name='запчасть'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Единица измерения запчасти.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_in_items', to='invoices.unit', verbose_name='единица измерения'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='version',
            field=models.ForeignKey(help_text='Версия накладной, из которой была получена эта строка.', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='invoices.invoiceversion', verbose_name='версия накладной'),
        ),
        migrations.AlterField(
            model_name='invoiceversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Дата и время создания версии.', verbose_name='создано'),
        ),
        migrations.AlterField(
            model_name='invoiceversion',
            name='file',
            field=models.FileField(help_text='Файл накладной в формате Excel.', upload_to=core.utils.invoice_file_path, validators=[core.validators.validate_invoice_file], verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='invoiceversion',
            name='invoice',
            field=models.ForeignKey(help_text='Накладная, к которой относится эта версия.', on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='invoices.invoice', verbose_name='накладная'),
        ),
        migrations.AlterField(
            model_name='invoiceversion',
            name='version',
            field=models.PositiveIntegerField(help_text='Порядковый номер версии накладной.', verbose_name='версия'),
        ),
        migrations.AlterField(
            model_name='reportmonth',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время первого закрытия отчётного периода.', null=True, verbose_name='дата закрытия'),
        ),
        migrations.AlterField(
            model_name='reportmonth',
            name='end_date',
            field=models.DateField(blank=True, help_text='Последний день отчётного периода.', null=True, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='reportmonth',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, help_text='Дата и время последнего изменения.', verbose_name='изменено'),
        ),
        migrations.AlterField(
            model_name='reportmonth',
            name='month',
            field=models.IntegerField(help_text='Месяц отчётного периода.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='месяц'),
        ),
        migrations.AlterField(
            model_name='reportmonth',
            name='start_date',
            field=models.DateField(help_text='Первый день отчётного периода.', verbose_name='дата начала'),
        ),
        migrations.AlterField(
            model_name='reportmonth',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт'), ('editing', 'На редакции')], default='open', help_text='Текущий статус отчётного периода.', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='reportmonth',
            name='year',
            field=models.IntegerField(default=2026, help_text='Год отчётного периода.', validators=[django.core.validators.MinValueValidator(2000)], verbose_name='год'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('number', 'date', 'company'), name='uniq_invoice_number_date_per_company'),
        ),
    ]
